top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules/loggers
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules/loggers
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules/loggers

include $(top_srcdir)/build/special.mk

