top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/server/mpm
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/server/mpm
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
