top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules/generators
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules/generators
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules/generators

include $(top_srcdir)/build/special.mk

