top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules/core
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules/core
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules/core

include $(top_srcdir)/build/special.mk

