top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/os
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/os
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
