top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules/metadata
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules/metadata
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules/metadata

include $(top_srcdir)/build/special.mk

