top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules/http
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules/http
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules/http

include $(top_srcdir)/build/special.mk

