top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules/cache
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules/cache
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules/cache

include $(top_srcdir)/build/special.mk

