top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules/slotmem
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules/slotmem
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules/slotmem
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
