top_srcdir   = /home/pcisse200/tools2021/httpd-2.4.46
top_builddir = /home/pcisse200/tools2021/httpd-2.4.46
srcdir       = /home/pcisse200/tools2021/httpd-2.4.46/modules
builddir     = /home/pcisse200/tools2021/httpd-2.4.46/modules
VPATH        = /home/pcisse200/tools2021/httpd-2.4.46/modules

SUBDIRS = $(MODULE_DIRS)
CLEAN_SUBDIRS = $(MODULE_CLEANDIRS)

include $(top_builddir)/build/rules.mk

